---
version: '3.7'
services:
  mysql:
    image: mariadb:latest
    container_name: ppapt-mariadb
    restart: always
    volumes:
      - /data/ppapt/mysql/var/lib/mysql:/var/lib/mysql
      - ./override-mariadb-docker.cnf:/etc/mysql/conf.d/docker.cnf
    networks:
      ppapt:
        aliases:
          - mysql
          - mariadb
        ipv4_address: 172.27.72.2
    environment:
      - MYSQL_ROOT_PASSWORD=T0pS3cret
      - MYSQL_USER=ppapt
      - MYSQL_PASSWORD=ppapt
      - MYSQL_DATABASE=ppapt
    ports:
      - 3306:3306
  postgres:
    image: postgres:latest
    container_name: ppapt-postgres
    restart: always
    volumes:
      - /data/ppapt/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      ppapt:
        aliases:
          - postgres
          - postgresql
        ipv4_address: 172.27.72.3
    environment:
      - POSTGRES_PASSWORD=T0pS3cret
    ports:
      - 5432:5432
  liquibase:
    image: registry.ott-consult.de/ppapt/liquibase:latest
    depends_on:
      - mysql
      - postgres
    restart: "no"
    networks:
      ppapt:
        aliases:
          - liquibase
        ipv4_address: 172.27.72.4
    environment:
      - MYSQL_HOST=172.27.72.2
      - MYSQL_ROOT_PASSWORD=T0pS3cret
      - POSTGRES_HOST=172.27.72.3
      - POSTGRES_PASSWORD=T0pS3cret

networks:
  ppapt:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.72.0/24
    external: false
