#!/bin/bash
set -x

cd $APP_HOME

if [ -d ppapt-database ]; then
   cd ppapt-database
   git pull
else
  git clone https://github.com/ppapt/ppapt-database.git
  cd ppapt-database
fi
wait4port -s ${MYSQL_HOST} -p 3306
# wait for the user creation
sleep 30
mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=${MYSQL_HOST} -P 3306 <mysql/create_db.sql

wait4port -s ${POSTGRES_HOST} -p 5432
echo "${POSTGRES_HOST}:5432:*:postgres:${POSTGRES_PASSWORD}" >~/.pgpass
chmod 0600 ~/.pgpass
psql -U postgres -h ${POSTGRES_HOST} -p 5432 -f postgres/create_db.sql

cd /usr/lib/liquibase

JAVA=/usr/java/latest/jre/bin/java
LIQUIBASE_HOME=/usr/lib/liquibase
CP='.'
for i in "$LIQUIBASE_HOME"/liquibase*.jar; do
    CP="$CP:$i"
done
CP="$CP:$LIQUIBASE_HOME/lib/"
for i in "$LIQUIBASE_HOME"/lib/*.jar; do
    CP="$CP:$i"
done
CP="$CP:$LIQUIBASE_HOME/drivers/"
for i in "$LIQUIBASE_HOME"/lib/*.jar; do
    CP="$CP:$i"
done



JAVA_CMD="${JAVA} -cp ${CP} $LIQUIBASE_JAVA_OPTIONS -jar liquibase.jar"

PARAMS="--driver=com.mysql.jdbc.Driver --classpath='.:lib/*.jar:drivers/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar' --changeLogFile=liquibase.changeset.sql --url='jdbc:mysql://${MYSQL_HOST}:3306/ppapt?autoReconnect=true&useSSL=false' --userName=ppapt --password=ppapt"
${JAVA_CMD} ${PARAMS} update


PARAMS="--driver=org.postgresql.Driver --classpath='.:lib/*.jar:drivers/postgresql-${POSTGRES_CONNECTOR_VERSION}.jar' --changeLogFile=liquibase.changeset.sql --url='jdbc:postgresql://${POSTGRES_HOST}:5432/ppapt' --userName=ppapt --password=ppapt"
${JAVA_CMD} ${PARAMS} update
