#!/bin/bash
set -x

cd $APP_HOME

if [ -d ppapt-database ]; then
   cd ppapt-database
   git pull
else
  git clone https://github.com/ppapt/ppapt-database.git
  cd ppapt-database
fi
wait4port -s ${MYSQL_HOST} -p 3306
# wait for the user creation
sleep 10
mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=${MYSQL_HOST} -P 3306 <mysql/create_db.sql

wait4port -s ${POSTGRES_HOST} -p 5432
echo "${POSTGRES_HOST}:5432:*:postgres:${POSTGRES_PASSWORD}" >~/.pgpass
chmod 0600 ~/.pgpass
psql -U postgres -h ${POSTGRES_HOST} -p 5432 -f postgres/create_db.sql


CMD="${LIQUIBASE_HOME}/liquibase"
#--classpath='.:lib/*.jar:drivers/mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar'
PARAMS="--logLevel=INFO --driver=org.mariadb.jdbc.Driver --changeLogFile=liquibase.changeset.sql --url=jdbc:mariadb://${MYSQL_HOST}:3306/ppapt?autoReconnect=true&useSSL=false --username=ppapt --password=ppapt"
${CMD} ${PARAMS} update


PARAMS="--logLevel=INFO --driver=org.postgresql.Driver --changeLogFile=liquibase.changeset.sql --url=jdbc:postgresql://${POSTGRES_HOST}:5432/ppapt --username=ppapt --password=ppapt"
${CMD} ${PARAMS} update
